In [ ]:
## load the pickle file

import pickle
import tensorflow as tf
from tensorflow.keras.models import load_model
import numpy as np
import pandas as pd

ModuleNotFoundError: No module named 'tensorflow.keras.Models'

In [2]:
## load the trained model, scale and onehot encoder objects file


model  = load_model('model2.keras')


## load the encoder and scaler objects

with open('onehot_encoder_geo.pkl', 'rb') as file:
    label_encoder_geo = pickle.load(file)
                                
with open('scaler.pkl', 'rb') as file:
    scaler = pickle.load(file)
                       
with open('label_encoder_gender.pkl', 'rb') as file:
    label_encoder_gender = pickle.load(file)

In [3]:
## example input data for prediction
input_data = {
  "CreditScore": 650,
  "Geography": "France",
  "Gender": "Male",
  "Age": 38,
  "Tenure": 5,
  "Balance": 75000.50,
  "NumOfProducts": 2,
  "HasCrCard": 1,
  "IsActiveMember": 1,
  "EstimatedSalary": 92000.00
}

In [4]:
input_df = pd.DataFrame([input_data])
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,650,France,Male,38,5,75000.5,2,1,1,92000.0

In [5]:
## one hot encode Geography

geo_encoded = label_encoder_geo.transform([[input_data['Geography']]]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded, columns=label_encoder_geo.get_feature_names_out(['Geography']))  
geo_encoded_df

c:\Users\priya\Desktop\Gen AI\ANN_Classification\venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [6]:
input_data = pd.concat([input_df.reset_index(drop=True), geo_encoded_df.reset_index(drop=True)], axis=1)
input_data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,650,France,Male,38,5,75000.5,2,1,1,92000.0,1.0,0.0,0.0

In [7]:
## encode gender variable

input_df["Gender"] =label_encoder_gender.transform(input_df["Gender"])
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,650,France,1,38,5,75000.5,2,1,1,92000.0

In [8]:
## concatenate encoded geography columns with input data

input_df = pd.concat([input_df.drop("Geography", axis=1), geo_encoded_df], axis=1)
input_df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,650,1,38,5,75000.5,2,1,1,92000.0,1.0,0.0,0.0

In [9]:
## scaling the input data

input_Scaled = scaler.transform(input_df)

In [10]:
## predict churn

prediction = model.predict(input_Scaled)
print(prediction)

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[0.02164445]]

In [11]:
prediction_proba = prediction[0][0]

In [12]:
prediction_proba

np.float32(0.021644449)